# docker-debian-rsync - Docker configuration for rsync on Debian
# Written in 2024 by Hubert Bielenia <hbielenia@users.noreply.github.com>
# To the extent possible under law, the author(s) have dedicated all copyright and related
# and neighboring rights to this software to the public domain worldwide. This software
# is distributed without any warranty.
# You should have received a copy of the CC0 Public Domain Dedication along with this software.
# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

name: docker
on:
  workflow_call:
    inputs:
      debian_version:
        type: string
        required: true
      latest:
        type: boolean
        default: false
      push:
        type: boolean
        default: false
env:
  RSYNC_VERSION_MINOR: '3.2'
  RSYNC_VERSION_PATCH: '3'
  RSYNC_VERSION_PACKAGE: '4'
  RSYNC_VERSION_DEBIAN: 'deb11u1'
  DOCKERHUB_REPO: ${{ vars.DOCKERHUB_USERNAME }}/debian-rsync
  GHCR_REPO: ghcr.io/${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build Docker image
        uses: hbielenia/docker-build-action@7211d36e8ed0a62e6ef2f8610b734896e93d8190 # 0.2.0
        with:
          dockerfile: ./dockerfiles/${{ inputs.debian_version }}.Dockerfile
          tags: ${{ env.DOCKERHUB_REPO }}:latest
      - name: Test the built image
        run: docker run --rm ${{ env.DOCKERHUB_REPO }}:latest mypy --version
  upload:
    if: inputs.push
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # 3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # 3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        uses: hbielenia/docker-build-action@7211d36e8ed0a62e6ef2f8610b734896e93d8190 # 0.2.0
        with:
          dockerfile: ./dockerfiles/${{ inputs.debian_version }}.Dockerfile
          from_cache: '1'
          push: '1'
          tags: >-
            ${{ env.DOCKERHUB_REPO }}:${{ env.RSYNC_VERSION_MINOR }}-${{ inputs.debian_version }},
            ${{ env.DOCKERHUB_REPO }}:${{ env.RSYNC_VERSION_MINOR }}.${{ env.RSYNC_VERSION_PATCH }}-${{ inputs.debian_version }},
            ${{ env.DOCKERHUB_REPO }}:${{ env.RSYNC_VERSION_MINOR }}.${{ env.RSYNC_VERSION_PATCH }}-${{ env.RSYNC_VERSION_PACKAGE }}-${{ inputs.debian_version }},
            ${{ env.DOCKERHUB_REPO }}:${{ env.RSYNC_VERSION_MINOR }}.${{ env.RSYNC_VERSION_PATCH }}-${{ env.RSYNC_VERSION_PACKAGE }}-${{ env.RSYNC_VERSION_DEBIAN }}-${{ inputs.debian_version }},
            ${{ env.GHCR_REPO }}:${{ env.RSYNC_VERSION_MINOR }}-${{ inputs.debian_version }},
            ${{ env.GHCR_REPO }}:${{ env.RSYNC_VERSION_MINOR }}.${{ env.RSYNC_VERSION_PATCH }}-${{ inputs.debian_version }},
            ${{ env.GHCR_REPO }}:${{ env.RSYNC_VERSION_MINOR }}.${{ env.RSYNC_VERSION_PATCH }}-${{ env.RSYNC_VERSION_PACKAGE }}-${{ inputs.debian_version }},
            ${{ env.GHCR_REPO }}:${{ env.RSYNC_VERSION_MINOR }}.${{ env.RSYNC_VERSION_PATCH }}-${{ env.RSYNC_VERSION_PACKAGE }}-${{ env.RSYNC_VERSION_DEBIAN }}-${{ inputs.debian_version }},
      - name: Push generic tags
        if: inputs.latest
        uses: hbielenia/docker-build-action@7211d36e8ed0a62e6ef2f8610b734896e93d8190 # 0.2.0
        with:
          dockerfile: ./dockerfiles/${{ env.DEBIAN_VERSION }}.Dockerfile
          from_cache: '1'
          push: '1'
          tags: >-
            ${{ env.DOCKERHUB_REPO }}:latest,
            ${{ env.DOCKERHUB_REPO }}:${{ env.RSYNC_VERSION_MINOR }},
            ${{ env.DOCKERHUB_REPO }}:${{ env.RSYNC_VERSION_MINOR }}.${{ env.RSYNC_VERSION_PATCH }},
            ${{ env.GHCR_REPO }}:latest,
            ${{ env.GHCR_REPO }}:${{ env.RSYNC_VERSION_MINOR }},
            ${{ env.GHCR_REPO }}:${{ env.RSYNC_VERSION_MINOR }}.${{ env.RSYNC_VERSION_PATCH }},
